import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next";
import { ThemeProvider } from "@/components/theme-provider";
import { NavBar } from "@/components/nav-bar";

const inter = Inter({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<NuqsAdapter>
			<TRPCReactProvider>
				<html lang="en" suppressHydrationWarning>
					<body className={`${inter.className} antialiased`}>
						<ThemeProvider
							attribute="class"
							defaultTheme="system"
							themes={["light", "dark", "system", "tangerine-light", "tangerine-dark"]}
							enableSystem
							disableTransitionOnChange
						>
							<Toaster />

							<NavBar />

							{children}
						</ThemeProvider>
					</body>
				</html>
			</TRPCReactProvider>
		</NuqsAdapter>
	);
}
